include config.mk

all: libnctietue3.so

nctietue3.o: nctietue3.c nctietue3.h internals.h load_data.h config.mk
	$(CC) $(CFLAGS) -o $@ -c $<

functions.o: functions.c function_wrappers.c config.mk nctietue3.h
	$(CC) $(CFLAGS) -o $@ -c $<

libnctietue3.so: nctietue3.o functions.o
	$(CC) -o $@ -shared $^ -lnetcdf

autogenerated:
	mkdir -p autogenerated

functions.c: make_functions.pl functions.in.c | autogenerated
	./$<

function_wrappers.c: make_functions1.pl
	./$<

clean:
	rm -rf *.o autogenerated functions.c function_wrappers.c libnctietue.so

install: libnctietue3.so
	mkdir -p $(includedir) $(libdir)
	cp nctietue3.h $(includedir)
	cp libnctietue3.so $(libdir)

uninstall:
	rm -f $(includedir)/nctietue3.h $(libdir)/libnctietue3.so
